In [2]:
import numpy as np

def print_ndarray_info(x,xname='x'):
    print(f'{xname} =\n{x}')
    print(f'type({xname}) = {type(x)}')
    print(f'{xname}.dtype = {x.dtype}')
    print(f'{xname}.shape = {x.shape}')

In [3]:
x = np.array([3, 1, 4, 1, 5])
print_ndarray_info(x,'x')

x =
[3 1 4 1 5]
type(x) = <class 'numpy.ndarray'>
x.dtype = int64
x.shape = (5,)


In [7]:
y = np.linspace([0, 10, 50], [5, 15, 100], 6)
print_ndarray_info(y,'y')

y =
[[  0.  10.  50.]
 [  1.  11.  60.]
 [  2.  12.  70.]
 [  3.  13.  80.]
 [  4.  14.  90.]
 [  5.  15. 100.]]
type(y) = <class 'numpy.ndarray'>
y.dtype = float64
y.shape = (6, 3)


In [9]:
z = np.arange(0, 1, 0.1)
print_ndarray_info(z,'z')

z =
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
type(z) = <class 'numpy.ndarray'>
z.dtype = float64
z.shape = (10,)


In [21]:
zero_array = np.zeros((3,3))
print(zero_array)
print(zero_array.shape)  # Notice no paranthesis.

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [14]:
# Implement the function create_seq that returns a one-dimensional NumPy ndarray containing the sequence 0., 0.01, 0.02, ... , 0.98, 0.99, 1.
import numpy as np

def create_seq():
    """
    Returns: a numpy ndarray containing 0., 0.01, 0.02, ... 0.98, 0.99, 1.
    """
    #### BEGIN SOLUTION ####
    return np.linspace(0, 1, 101)
    #### END SOLUTION ####

In [15]:
seq = create_seq()
print_ndarray_info(seq,'seq')

seq =
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]
type(seq) = <class 'numpy.ndarray'>
seq.dtype = float64
seq.shape = (101,)


**Reshaping and Slicing DOES NOT create/copy new data for ndarrays!!**

In [16]:
a    = np.array([ 0., 1., -2.,  3.])
acol = a.reshape((4,1))
b    = np.array([2., 4., 3., -4.])
c    = 3.
K    = np.array([[2., 3., -1., 0.],[-1., 2., 4., 0.5]])

print(f'a   = {a}')
print(f'acol = \n{acol}')
print(f'b   = {b}')
print(f'c   = {c}')
print(f'K   = \n{K}\n')

print(f'a+b  = {a+b}\n')
print(f'a*b  = {a*b}\n')
print(f'a**b = {a**b}\n')

print(f'c+b  = {c+b}\n')
print(f'c*b  = {c*b}\n')
print(f'c**b = {c**b}\n')
print(f'b**c = {b**c}\n')

print(f'a.min() = {a.min()}\n')
print(f'a.max() = {a.max()}\n')

print(f'K.min()        = {K.min()}\n')
print(f'K.max(axis=0)  = {K.max(axis=0)}\n')
print(f'K.sum(axis=1)  = {K.sum(axis=1)}\n')
print(f'K.prod(axis=0) = {K.prod(axis=0)}\n')

print(f'K@a = \n{K@a}\n')

print(f'K@acol = \n{K@acol}\n')

a   = [ 0.  1. -2.  3.]
acol = 
[[ 0.]
 [ 1.]
 [-2.]
 [ 3.]]
b   = [ 2.  4.  3. -4.]
c   = 3.0
K   = 
[[ 2.   3.  -1.   0. ]
 [-1.   2.   4.   0.5]]

a+b  = [ 2.  5.  1. -1.]

a*b  = [  0.   4.  -6. -12.]

a**b = [ 0.          1.         -8.          0.01234568]

c+b  = [ 5.  7.  6. -1.]

c*b  = [  6.  12.   9. -12.]

c**b = [9.0000000e+00 8.1000000e+01 2.7000000e+01 1.2345679e-02]

b**c = [  8.  64.  27. -64.]

a.min() = -2.0

a.max() = 3.0

K.min()        = -1.0

K.max(axis=0)  = [2.  3.  4.  0.5]

K.sum(axis=1)  = [4.  5.5]

K.prod(axis=0) = [-2.  6. -4.  0.]

K@a = 
[ 5.  -4.5]

K@acol = 
[[ 5. ]
 [-4.5]]



In [38]:
A = np.array( [ [1,2,3], [4,5,6] ] )
print(A)
print(A[1, 1])
print(A[1][1])
print(A[0,])
print(A[0][:])
print(A[:][0])
print(A[0, :])
print(A[:, 0])

[[1 2 3]
 [4 5 6]]
5
5
[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[1 4]


$A = \left[ \begin{array}{ccc} 1 &  -1 &  0 \\ -1 &  2 &  -1 \\ 0 &  -1 &  2 \end{array} \right]$

In [2]:
import numpy as np


def create_A():
    """
    Returns: a numpy ndarray representing the matrix specified in the exercise
    """
    #### BEGIN SOLUTION ####
    A = np.array([[1, -1, 0], [-1, 2, -1], [0, -1, 2]])
    return A
    #### END SOLUTION ####

create_A()

array([[ 1, -1,  0],
       [-1,  2, -1],
       [ 0, -1,  2]])

In [3]:
import numpy as np


def give_x():
    """
    Returns: a numpy ndarray containing the solution to Ax = b,
        for A and x given in the exercise
    """
    #### BEGIN SOLUTION ####
    x = np.array([6, 5, 3])
    return x
    #### END SOLUTION ####

In [4]:
give_x()

array([6, 5, 3])