In [43]:
import time
import numpy as np

def myGE_vec(K, f):
    """
    Gaussian elimination (with vectorization)
    """
    m,n = K.shape
    assert m == n, "Non-square matrix"

    u = np.zeros(n)
    print("Shape of u:", u.shape)

    # Extended matrix with the right-hand side as last column
    A = np.zeros((n,n+1))
    A[:,0:n] = K
    A[:,n] = f
    print("A shape:", A.shape)

    # Elimination of nonzero elements below the diagonal
    print("A at the beginning:")
    print(A)
    print("**************************************")
    for i in range(n):  # for each ROW i:
        assert A[i,i] != 0.0, "Zero pivot detected"

        # Calculate Li which is the vector of all Lji values (for all values of j)
        Li = A[i+1:, i] / A[i, i]  # multiplier for row i. We need to update 
                                # A[j, :] = A[j, :] - A[i, :] * Li[j] for all rows j >= i+1
        # Li is COLUMN vector!
        print("Shape of Li:", Li.shape)
        
        
        # Update A[i+1:n,i+1:]
        # Hint: consider using an outer product of Li and the relevant
        #       portion of the A matrix (np.outer is the NumPy command)
        A[i+1:, i:] -= np.outer(Li, A[i, i:])
        print("A at iteration", i, ":")
        print(A.round(4))
        print("---------------------------------------------------------------")
    print("Extended matrix A' after eliminations (upper triangular):")
    print(A.round(4))

                
    # Back substitution
    u[n-1] = A[n-1,n]/A[n-1,n-1]
    print("u[n-1] =", u[n-1])

    for i in range(n-2,-1,-1):
        # Calculate u[i].
        # Hint: the np.dot command will be useful
        u[i] = (A[i, n] - np.dot(A[i, i+1:n], u[i+1:])) / A[i, i]
        print(f"u[{i}] =", u[i])

    return u

In [44]:
K = np.array([[1, 1, 5, 2], [9, 3, 4, 9], [6, 9, 5, 6], [7, 8, 5, 9]])
b = np.array([3, 5, 7, 9])
print("K:")
print(K)
print("-------------")
print("b:")
print(b.reshape(4, 1))

K:
[[1 1 5 2]
 [9 3 4 9]
 [6 9 5 6]
 [7 8 5 9]]
-------------
b:
[[3]
 [5]
 [7]
 [9]]


In [45]:
start = time.time()

solution = myGE_vec(K, b)
print("____________________________________________________________")
print("Solution u:")
print(solution.reshape(4, 1))
print("____________________________________________________________")
epsilon = 0.001
print("K =", K)
print("solution", solution)
print("K@solution", K@solution)
print("Is the solution correct within an accuracy of", epsilon, "?")
print(abs(K@solution - b) <= epsilon)

end = time.time()

print("------------------------------")
print("Runtime =", round((end-start), 4), "seconds")

Shape of u: (4,)
A shape: (4, 5)
A at the beginning:
[[1. 1. 5. 2. 3.]
 [9. 3. 4. 9. 5.]
 [6. 9. 5. 6. 7.]
 [7. 8. 5. 9. 9.]]
**************************************
Shape of Li: (3,)


ValueError: operands could not be broadcast together with shapes (3,5) (5,3) (3,5) 

In [42]:
np.linalg.solve(K, b)

array([-0.76923077,  0.44505495,  0.23626374,  1.07142857])