In [93]:
import numpy as np

def myGE_vec(K, f):
    """
    Gaussian elimination (with vectorization)
    """
    m,n = K.shape
    assert m == n, "Non-square matrix"

    u = np.zeros(n)

    # Extended matrix with the right-hand side as last column
    A = np.zeros((n,n+1))
    A[:,0:n] = K
    A[:,n] = f

    # Elimination of nonzero elements below the diagonal
    print("A at the beginning:")
    print(A)
    print("**************************************")
    for i in range(n):  # for each ROW i:
        assert A[i,i] != 0.0, "Zero pivot detected"

        # Calculate Li which is the vector of all Lji values (for all values of j)
        Li = A[i+1:, i] / A[i, i]  # multiplier for row i. We need to update 
                                # A[j, :] = A[j, :] - A[i, :] * Li[j] for all rows j >= i+1
        # Li is COLUMN vector!
        print("Shape of Li:", Li.shape)
        
        
        # Update A[i+1:n,i+1:]
        # Hint: consider using an outer product of Li and the relevant
        #       portion of the A matrix (np.outer is the NumPy command)
        # TODO
        A[i+1:n, i:] -= np.outer(Li, A[i, i:])
        print("A at iteration", i, ":")
        print(A)
        print("---------------------------------------------------------------")
    print("Extended matrix A' after eliminations (upper triangular):")
    print(A)

                
    # Back substitution
    u[n-1] = A[n-1,n]/A[n-1,n-1]

    for i in range(n-2,-1,-1):
        # Calculate u[i].
        # Hint: the np.dot command will be useful
        u[i] = (A[n-2, n] - A[n-2, n-1]*u[i+1]) / A[n-2, n-2]

    return u

In [94]:
K = np.array([[4, 8, 2], [2, 1, 3], [5, 5, 5]])
b = np.array([5, 5, 10])

solution = myGE_vec(K, b)
print("____________________________________________________________")
print("Solution u =", solution)
print("____________________________________________________________")
epsilon = 0.01
print("Is the solution correct?")
print(K*solution <= abs(b - epsilon))

A at the beginning:
[[ 4.  8.  2.  5.]
 [ 2.  1.  3.  5.]
 [ 5.  5.  5. 10.]]
**************************************
Shape of Li: (2,)
A at iteration 0 :
[[ 4.    8.    2.    5.  ]
 [ 0.   -3.    2.    2.5 ]
 [ 0.   -5.    2.5   3.75]]
---------------------------------------------------------------
Shape of Li: (1,)
A at iteration 1 :
[[ 4.          8.          2.          5.        ]
 [ 0.         -3.          2.          2.5       ]
 [ 0.          0.         -0.83333333 -0.41666667]]
---------------------------------------------------------------
Shape of Li: (0,)
A at iteration 2 :
[[ 4.          8.          2.          5.        ]
 [ 0.         -3.          2.          2.5       ]
 [ 0.          0.         -0.83333333 -0.41666667]]
---------------------------------------------------------------
Extended matrix A' after eliminations (upper triangular):
[[ 4.          8.          2.          5.        ]
 [ 0.         -3.          2.          2.5       ]
 [ 0.          0.         -0.8

In [82]:
for i in range(5,-1,-1):
    print(i)

5
4
3
2
1
0
